/**
 * Gates for the synthetic corpus generator (`scripts/generate-corpus.ts`).
 *
 * The generator exists so scale and browser-cost benchmarks can be run against
 * a corpus larger than a fixture, and two properties make its numbers mean
 * anything: the corpus is reproducible, and its shape is the shape the
 * benchmark claims to measure. Both are facts about written bytes, so every
 * gate here reads the files.
 *
 * **The golden digest is the determinism gate.** `{ notes: 24, seed: 7 }` was
 * generated by this repository's own generator before `topology` and `metadata`
 * existed, and hashed as sha256 over every written file in byte-wise relative
 * path order, feeding each path's UTF-8 bytes and then its bytes. A refactor
 * that reorders one draw from the seeded RNG still produces a plausible corpus,
 * and this is the instrument that says so. `docs/gate-reading.md` case 5 is why
 * the helper below is written to the same recipe: the digest has to fail when
 * the generator changes, and stay equal when only the options are added.
 *
 * **The two workload options are checked on disk, not in the options.** Sparse
 * is asserted as a low-degree graph and as a flatter corpus than the skewed
 * default of the same size, because "no hubs" is a property of the edges a
 * benchmark traverses, not of the flag. Metadata is asserted as frontmatter on
 * every note — tags, aliases, a mixed-script heading every 25th — with the
 * withheld notes still carrying `publish: false`, because the tag and search
 * workloads read the files the build reads.
 */

import { createHash } from 'node:crypto';
import { mkdir, mkdtemp, readdir, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, relative, sep } from 'node:path';
import assert from 'node:assert/strict';
import { test } from 'vitest';

import { generateCorpus } from '../scripts/generate-corpus.ts';
import type { CorpusOptions, GeneratedCorpus } from '../scripts/generate-corpus.ts';

/**
 * sha256 of `{ notes: 24, seed: 7 }` under the defaults.
 *
 * Recorded before the workload options were added, by the recipe `digestOf`
 * implements. Do not replace this number to make a failing run green: it is the
 * statement that the default corpus has not moved.
 */
const GOLDEN_DIGEST = '1785b6f3f57042e5dc49c3ba5c92c7d29008a07c3731c6740e566e40adba2e9b';

/** The default-result counts recorded beside {@link GOLDEN_DIGEST}. */
const GOLDEN_RESULT: GeneratedCorpus = {
  files: 25,
  published: 21,
  withheld: 3,
  assets: 1,
  bytes: 14_300,
};

interface WrittenCorpus {
  result: GeneratedCorpus;
  files: Map<string, Buffer>;
}

/** Every file under a directory, recursively. */
async function filesUnder(directory: string): Promise<string[]> {
  const found: string[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) found.push(...(await filesUnder(path)));
    else found.push(path);
  }
  return found;
}

/**
 * Generate into a scratch directory and return the result plus every byte.
 *
 * The scratch directory is removed before returning; the buffer map is the
 * corpus. Paths are keyed corpus-relative and POSIX-separated so the digest is
 * the same on every host.
 */
async function write(options: CorpusOptions): Promise<WrittenCorpus> {
  const root = await mkdtemp(join(tmpdir(), 'generate-corpus-'));
  try {
    const directory = join(root, 'corpus');
    await mkdir(directory, { recursive: true });
    const result = await generateCorpus(directory, options);
    const files = new Map<string, Buffer>();
    for (const file of await filesUnder(directory)) {
      files.set(relative(directory, file).split(sep).join('/'), await readFile(file));
    }
    return { result, files };
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

/** Corpus files in byte-wise path order, which is the digest's order. */
function entriesOf(files: ReadonlyMap<string, Buffer>): [string, Buffer][] {
  return [...files].sort(([a], [b]) => Buffer.compare(Buffer.from(a, 'utf8'), Buffer.from(b, 'utf8')));
}

/** sha256 over a corpus: each path's UTF-8 bytes then that file's bytes, sorted. */
function digestOf(files: ReadonlyMap<string, Buffer>): string {
  const hash = createHash('sha256');
  for (const [path, bytes] of entriesOf(files)) {
    hash.update(Buffer.from(path, 'utf8'));
    hash.update(bytes);
  }
  return hash.digest('hex');
}

/**
 * The outgoing links in one note: wikilinks in all their forms plus the
 * Markdown form. The deliberately absent `[[word-<index>-absent]]` links are
 * excluded — they are the degrade-to-text branch, not an edge.
 */
function outgoingLinks(markdown: string): string[] {
  const links: string[] = [];
  for (const [, target] of markdown.matchAll(/\[\[([^\]|]+)(?:\|[^\]]*)?\]\]/g)) {
    if (!target!.endsWith('-absent')) links.push(target!);
  }
  for (const [, href] of markdown.matchAll(/\[[^\]]*\]\(([^)]+)\)/g)) links.push(href!);
  return links;
}

/** The Markdown notes of a corpus, path and text, in path order. */
function notesOf(files: ReadonlyMap<string, Buffer>): [string, string][] {
  return entriesOf(files)
    .filter(([path]) => path.endsWith('.md'))
    .map(([path, bytes]) => [path, bytes.toString('utf8')]);
}

test('the default corpus reproduces the recorded golden digest byte for byte', async () => {
  const first = await write({ notes: 24, seed: 7 });
  const second = await write({ notes: 24, seed: 7 });

  assert.equal(
    digestOf(first.files),
    GOLDEN_DIGEST,
    'the default corpus changed; the seeded RNG order or the bytes it writes moved',
  );
  assert.deepEqual(
    entriesOf(first.files),
    entriesOf(second.files),
    'two runs of the same options produced different files',
  );
  assert.deepEqual(
    first.result,
    GOLDEN_RESULT,
    'the default result counts moved even though the bytes are pinned',
  );

  // Non-vacuity: a helper that hashed an empty map would match no digest below,
  // but a gate whose corpus is one file could still pass a wrong recipe, so
  // the recorded corpus size is asserted rather than assumed.
  assert.equal(first.files.size, GOLDEN_RESULT.files, 'the golden corpus no longer has its recorded size');
  assert.equal(first.result.published + first.result.withheld, 24, 'the golden corpus lost its note partition');
});

test('the sparse topology caps every note at two links and flattens the skewed graph', async () => {
  const sparse = await write({ notes: 120, seed: 7, topology: 'sparse' });
  const skewed = await write({ notes: 120, seed: 7 });

  const sparseCounts = notesOf(sparse.files).map(([, text]) => outgoingLinks(text).length);
  const skewedCounts = notesOf(skewed.files).map(([, text]) => outgoingLinks(text).length);
  assert.equal(sparseCounts.length, 120, 'the sparse corpus is not the size it was generated at');

  // Every note links one or two others, and no note is a hub. The lower bound
  // is asserted too: the constant-out-degree version of this corpus would
  // satisfy an upper bound alone while measuring a graph no vault has.
  assert.ok(
    Math.max(...sparseCounts) <= 2,
    `a sparse note links ${Math.max(...sparseCounts)} others, more than the topology allows`,
  );
  assert.ok(
    Math.min(...sparseCounts) >= 1,
    'a sparse note links nothing, so its out-degree was silently deleted by a skipped self-target',
  );

  // Non-vacuity: the contrast has to exist in the other corpus, or the sparse
  // bound above is compared to nothing.
  assert.ok(
    Math.max(...skewedCounts) > 2,
    'the skewed default produced no note above two links, so the two topologies are not different',
  );
  const total = (counts: readonly number[]): number => counts.reduce((sum, count) => sum + count, 0);
  assert.ok(
    total(sparseCounts) < total(skewedCounts),
    `sparse has ${total(sparseCounts)} links and skewed ${total(skewedCounts)}; sparse is not the flatter graph`,
  );

  assert.equal(sparse.result.published + sparse.result.withheld, 120, 'sparse lost a note');
});

test('metadata gives every note tags, an alias, and a mixed-script heading every 25th', async () => {
  const first = await write({ notes: 200, seed: 7, metadata: true });
  const second = await write({ notes: 200, seed: 7, metadata: true });

  const notes = notesOf(first.files);
  assert.equal(notes.length, 200, 'the metadata corpus is not the size it was generated at');

  let withheld = 0;
  let mixedTitles = 0;
  const aliases = new Set<string>();
  for (const [path, text] of notes) {
    const front = /^---\n([\s\S]*?)\n---\n/.exec(text)?.[1];
    assert.ok(front !== undefined, `${path} has no frontmatter block, so metadata did not reach every note`);

    const tagLine = /^tags: \[(.+)\]$/m.exec(front)?.[1];
    assert.ok(tagLine !== undefined, `${path} has no tags`);
    const tags = tagLine!.split(', ');
    assert.equal(tags.length, 3, `${path} carries ${tags.length} tags rather than three`);
    assert.ok(
      tags.some((tag) => /[\u4e00-\u9fff]/u.test(tag)),
      `${path} has no CJK tag: ${tags.join(', ')}`,
    );

    const alias = /^aliases: \["alias-(\d+)"\]$/m.exec(front)?.[1];
    assert.ok(alias !== undefined, `${path} has no alias-<index>`);
    aliases.add(alias!);

    if (/^publish: false$/m.test(front!)) withheld += 1;
    if (/^# .*[\u4e00-\u9fff]/mu.test(text)) mixedTitles += 1;
  }

  // Non-vacuity for the withheld half: the 4% draw has to have produced at
  // least one, or "withheld notes still carry publish: false" is about no note.
  assert.ok(withheld > 0, 'no withheld note was generated, so the exclusion check is vacuous');
  assert.equal(withheld, first.result.withheld, 'files with publish: false disagree with the returned count');
  assert.equal(first.result.published + first.result.withheld, 200, 'metadata changed the note partition');
  assert.equal(
    mixedTitles,
    200 / 25,
    'the mixed-script heading count is not the one the every-25th rule predicts',
  );
  assert.equal(aliases.size, 200, 'aliases are not unique per note, so they cannot identify one');

  assert.equal(
    digestOf(first.files),
    digestOf(second.files),
    'two runs of metadata mode produced different corpora',
  );
});

test('topology and metadata leave the published/withheld partition untouched', async () => {
  const cases: readonly [string, CorpusOptions][] = [
    ['default', { notes: 60, seed: 11 }],
    ['sparse', { notes: 60, seed: 11, topology: 'sparse' }],
    ['metadata', { notes: 60, seed: 11, metadata: true }],
    ['sparse + metadata', { notes: 60, seed: 11, topology: 'sparse', metadata: true }],
  ];

  for (const [name, options] of cases) {
    const { result } = await write(options);
    assert.equal(result.published + result.withheld, 60, `${name} does not partition its notes`);
    assert.equal(result.files, 60 + result.assets, `${name} wrote a file it did not count`);
  }
});
